# Name Service
spring:
  application:
    name: retrieve-video-service
  cloud:
    config:
      env: default # optional
      label: master # optional
      uri: ${CONFIG_SERVER:http://localhost:8888} # optional

      